In [2]:
list1=[1,2,3,"hello"]
list2=[4,5,6,"india"]
list1.extend(list2)
print(list1)

[1, 2, 3, 'hello', 4, 5, 6, 'india']


###remove

### remove

In [3]:
list1.pop()
print(list1)

[1, 2, 3, 'hello', 4, 5, 6]


In [4]:
list1.reverse()
print(list1)

[6, 5, 4, 'hello', 3, 2, 1]


In [6]:
n=[2,6,1,8]
n.sort()
print(n)

[1, 2, 6, 8]


In [8]:
n.sort(reverse=True)
print(n)

[8, 6, 2, 1]


In [12]:
x=[10,20,30,40]
y=x.copy()
y[1]=777
print(x)
print(y)

[10, 20, 30, 40]
[10, 777, 30, 40]


In [13]:
a=[10,20,30]
b=[40,50,60]
c=a+b
print(c)

[10, 20, 30, 40, 50, 60]


In [14]:
x=["mite","mangalore","nitte"]
y=["mite","mangalore","nitte"]
x==y
x!=y
z=["mite","mangalore","nitte"]
x==z

True

In [17]:
m=[10,20,30,[50,60,70]]
m[2]
m[3][1]


60

In [18]:
m.clear()

In [20]:
n=[1,2,3,4]
print(4 in n)

True


In [22]:
words=["mite","mangalore","nitte"]
l=[w[0]for w in words]
print(l)

['m', 'm', 'n']


In [37]:
def prime(num):
    flag=0
    for i in range(2,num//2):
        if num%i==0:
            
            flag=1
            break
    if flag==1:
        print("not prime")
    else:
        print("prime")
num=int(input("enter a number"))    
prime(num)    

enter a number5
prime


In [38]:
seq=[1,2,3,4,5]
lambda var:var*2
list(map(lambda var:var*2,seq))

[2, 4, 6, 8, 10]

In [39]:
seq=[1,2,3,4,5]
lambda var:var*2
list(map(lambda var:var*2,seq))
list(filter(lambda item:item%2==0,seq))

[2, 4]

In [40]:
i=10
print(i)

10


In [41]:
import numpy as np
my_list=[1,2,3]
print(my_list)
np.array(my_list)

[1, 2, 3]


array([1, 2, 3])

In [43]:
my_matrix=[[1,2,3],[4,5,6],[7,8,9]]
print(my_matrix)
np.array(my_matrix)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [44]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [45]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [46]:
np.zeros(3)

array([0., 0., 0.])

In [47]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [49]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [50]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [51]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [52]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [53]:
np.random.rand(2)

array([0.424337  , 0.12775296])

In [54]:
np.random.rand(5,5)

array([[0.49491099, 0.1227164 , 0.52157081, 0.99661232, 0.16128177],
       [0.74593476, 0.52280408, 0.46517954, 0.96179866, 0.6167451 ],
       [0.2986217 , 0.84295747, 0.15206872, 0.80818934, 0.90717374],
       [0.20033347, 0.66363286, 0.57329461, 0.70835853, 0.2815456 ],
       [0.02003961, 0.10562533, 0.5917672 , 0.84644138, 0.51492219]])

In [55]:
np.random.randn(5,5)

array([[-0.16630453,  1.4235238 , -0.43617571,  0.25297592, -0.25825129],
       [-0.03142902,  0.15295872,  1.27163755, -0.8633955 , -1.00713508],
       [ 0.69102553, -0.98983937, -0.52733198,  1.02921515, -1.49467665],
       [ 0.68880725, -1.72108814,  1.46929352,  0.7161619 , -0.62618702],
       [-1.70059147, -0.22371776,  0.23928541, -1.6703168 ,  1.02841403]])

In [56]:
np.random.randint(1,100,10)

array([44, 74,  2, 62, 88, 65, 63, 44, 98,  5])

In [57]:
ar=np.random.randint(1,100,10)
print(ar)

[69 52 44 36 98 96 30 38 41 66]


In [58]:
runarr=np.random.randint(0,50,10)

In [59]:
print(runarr)

[17 44 40 34 13 32  4 26 12 42]


In [62]:
arr=np.arange(25)

In [63]:
runarr=np.random.randint(0,50,10)

In [64]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [65]:
runarr.max()


49

In [66]:
runarr.argmax()

9

In [67]:
runarr.argmin()

7

In [68]:
runarr.min()

2

In [69]:
arr.shape

(25,)

In [70]:
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [71]:
arr.reshape(1,25).shape

(1, 25)

In [72]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [73]:
arr.reshape(25,1).shape

(25, 1)

In [74]:
arr.dtype

dtype('int32')

In [75]:
arr=np.arange(0,10)

In [76]:
arr+arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [77]:
arr*arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [78]:
arr-arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [80]:
arr//arr

C:\Users\user\anaconda internship\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in floor_divide
  """Entry point for launching an IPython kernel.


array([0, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int32)

In [81]:
1/arr

C:\Users\user\anaconda internship\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [82]:
arr*3

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [83]:
arr**3

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

In [84]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [85]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [86]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [87]:
np.log(arr)

C:\Users\user\anaconda internship\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [88]:
arr=np.arange(0,11)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [89]:
arr[8]

8

In [90]:
arr[1:5]

array([1, 2, 3, 4])

In [91]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [92]:
arr[0:5]=100

In [93]:
print(arr)

[100 100 100 100 100   5   6   7   8   9  10]


In [94]:
arr>4

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [95]:
arr=np.arange(0,11)

In [96]:
arr>4

array([False, False, False, False, False,  True,  True,  True,  True,
        True,  True])

In [97]:
arr[arr>4]

array([ 5,  6,  7,  8,  9, 10])

In [98]:
np.zeros(12)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [99]:
np.ones(15)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [101]:
np.tens(5)

AttributeError: module 'numpy' has no attribute 'tens'

In [102]:
arr=np.arange(0,41)
arr+arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80])

In [104]:
ar=np.arange(0,9)

In [105]:
print(ar)

[0 1 2 3 4 5 6 7 8]


In [106]:
ar.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [109]:
ar=np.arange(1,26)
ar.reshape(5,5)


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [110]:
ar[ar>12]

array([13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25])

In [111]:
np.random.randn(25)

array([ 0.5938364 ,  1.38870032,  0.94937994, -1.08264833,  1.65523928,
       -0.58586668, -1.59223145,  0.51983982,  0.65858117,  1.2035947 ,
        0.07258209,  0.53222466, -0.71945219, -0.91380593,  0.79599218,
        0.53687197, -0.44077719, -0.18541321, -1.447138  ,  0.8528905 ,
        0.79452046, -1.2734181 , -0.62751748, -1.82604846,  1.15081726])

In [119]:
a=np.arange(10)
a[0:10]=5
print(a)

[5 5 5 5 5 5 5 5 5 5]
